# Generated by Django 4.2.16 on 2024-11-30 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.AutoField(primary_key=True, serialize=False)),
                ('train_type', models.CharField(max_length=100)),
                ('train_number', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Train',
                'verbose_name_plural': 'Trains',
                'db_table': 'train',
            },
        ),
        migrations.CreateModel(
            name='TrainSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('station', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('stop_order', models.IntegerField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_schedules.train')),
            ],
            options={
                'verbose_name': 'Train Schedule',
                'verbose_name_plural': 'Train Schedules',
                'db_table': 'train_schedule',
            },
        ),
    ]
