# Generated by Django 4.2.16 on 2024-12-01 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_schedules', '0002_rename_train_trainschedule_train_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainschedule',
            name='departure_date',
            field=models.DateField(default=datetime.date(2024, 11, 1)),
            preserve_default=False,
        ),
    ]
