# Generated by Django 4.2.16 on 2024-12-02 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seat', '0001_initial'),
        ('train_schedules', '0003_trainschedule_departure_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('passenger', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departure_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_schedules.trainschedule')),
                ('seat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seat.seat')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
