# Generated by Django 4.2.16 on 2024-12-02 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_ticket',
            table='user_ticket',
        ),
    ]
