# Generated by Django 4.2.16 on 2024-12-02 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train_schedules', '0003_trainschedule_departure_date'),
        ('seat', '0001_initial'),
        ('user', '0001_initial'),
        ('ticket', '0002_alter_user_ticket_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest_Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('passenger', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departure_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_schedules.trainschedule')),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.guest')),
                ('seat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seat.seat')),
            ],
            options={
                'db_table': 'guest_ticket',
            },
        ),
    ]
