# Generated by Django 4.2.16 on 2024-11-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyTicket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('departure_station', models.CharField(max_length=100)),
                ('arrival_station', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('adult_count', models.PositiveIntegerField(default=0)),
                ('child_count', models.PositiveIntegerField(default=0)),
                ('infant_count', models.PositiveIntegerField(default=0)),
                ('senior_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'my_ticket',
            },
        ),
    ]
