# Generated by Django 4.2.16 on 2024-12-02 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_myticket_schedule_myticket_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyTicket',
        ),
    ]
